print(bool(10))
print(bool(0))
print(bool(0.0))    
print(bool(''))
print(bool(' '))
print(True+True)
print(True+False)
print(False+False)
print(bool(None))
print(bool(False))
print(bool([]))
print(bool({}))
print(bool(()))
print(bool(range(0)))
print(bool(set()))
