cartoon=['ben10','doraemon','shinchan','tom and jerry','pooh']
print(cartoon)
cartoon.append('scooby doo')
print(cartoon)
cartoon.insert(2,'spiderman')
print(cartoon)
cartoon.remove('doraemon')
print(cartoon)
cartoon.pop(3)
print(cartoon)
cartoon.sort()
print(cartoon)
cartoon.reverse()
print(cartoon)
